[project]
name = "testbed-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Chandler", email = "adam.c02pro@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "adversarial-testbed",
]

[project.scripts]
testbed-cli = "testbed_cli:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
adversarial-testbed = { path = "../adversarial-testbed" }
